### ISSUE TITLE
Review Module 3 - PHP Coding Standards

### ISSUE THREAD

**Issue by AnitaYip** [AnitaYip/php-final#2]
@jlaswell @sbethi
PHP Coding standards module completed.

**Comment by jlaswell** [comment]
I haven't gotten the chance to read through this thoroughly, but awesome job getting this knocked out! I'll give some feedback as soon as I get time.

**Comment by AnitaYip** [comment]
Thanks @jlaswell . I have done this using IDE plugin for CodeSniffer. Would definitely love some feedback to know if something can be done in a better way.

**Comment by jlaswell** [comment]
PSR 2 looks great! The only thing I see is [this blank line](https://github.com/AnitaYip/php-final/blob/psr-2/model/User.php#L134) that is picked up by my sniffer. The rest of the app is good. There are some other comments related to the other module, so I'll post them on that issue. But I think you're good to close this one out!
